import Head from "next/head";
import { Inter } from "next/font/google";
import {
  TextField,
  Card,
  CardContent,
  Button,
  Box,
  Container,
} from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Container
          sx={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
          maxWidth="lg"
        >
          <Card sx={{ maxWidth: 392, maxHeight: 400 }}>
            <CardContent
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <TextField
                id="timer-input"
                label="Enter boiling timer"
                variant="standard"
              />
              <Button sx={{ marginLeft: 2 }} variant="contained">
                Start boiling
              </Button>
            </CardContent>
          </Card>
        </Container>
      </main>
    </>
  );
}
